name: Deploy HubSolidario

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy para hospedagem
    runs-on: ubuntu-latest

    steps:
      - name: Executar deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/remotoagenciaco/hubsolidario.remotoagencia.com.br
            ./deploy.sh